#==============================================================================
# Copyright (c) 2026 g0untlet. All rights reserved.
#==============================================================================
service_uri/mp-rest/url=http://localhost:8080
service_uri/mp-rest/scope=jakarta.enterprise.context.Dependent
