--==============================================================================
-- V1__baseline.sql
-- Initial Flyway baseline capturing the 0.3.0 schema as present in the live
-- DEV and PROD databases (extracted from the DEV DB via SCRIPT NODATA).
-- Existing databases are baselined at version 1 (see application.properties:
-- quarkus.flyway.baseline-on-migrate=true, quarkus.flyway.baseline-version=1)
-- and therefore do NOT re-execute this file. It only creates the schema on a
-- brand-new (empty) database.
--==============================================================================

CREATE TABLE positions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    accuracy    FLOAT(53),
    display_name VARCHAR(255),
    latitude    FLOAT(53) NOT NULL,
    longitude   FLOAT(53) NOT NULL,
    temperature FLOAT(24),
    timestamp   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id     VARCHAR(32) NOT NULL,
    weather_code INTEGER,
    address_type VARCHAR(255),
    city        VARCHAR(255),
    country     VARCHAR(255),
    house_number VARCHAR(255),
    osm_category VARCHAR(255),
    osm_name    VARCHAR(255),
    osm_type    VARCHAR(255),
    road        VARCHAR(255),
    comment     VARCHAR(255),
    elevation   FLOAT(24),
    tag         VARCHAR(32),
    uv_index    FLOAT(24),
    CONSTRAINT positions_pk PRIMARY KEY (id)
);