#==============================================================================
# Copyright (c) 2026 g0untlet. All rights reserved.
#==============================================================================

# Uber Jar
quarkus.package.jar.type=uber-jar

# Database Configuration
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/locator;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Hibernate ORM Configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file

# Test Database Configuration
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:locator_test;DB_CLOSE_DELAY=-1
%test.quarkus.http.test-port=0

# OpenAPI & Swagger UI Configuration
quarkus.swagger-ui.always-include=true

# HTTP Host Configuration
quarkus.http.host=0.0.0.0

# OpenStreetMap Nominatim Client Configuration
nominatim_uri/mp-rest/url=https://nominatim.openstreetmap.org

# Open-Meteo Weather Client Configuration
weather_uri/mp-rest/url=https://api.open-meteo.com

# Nur für echte/produktive IDs
allowed.user.ids=user123
# Zusätzliche IDs für Entwicklungs- und Test-Profile
%dev.allowed.user.ids=validUser,noAccuracyUser,geoUser,geoFailUser,stUser,user123,df22,mlf26
%test.allowed.user.ids=validUser,noAccuracyUser,geoUser,geoFailUser,stUser,user123,df22,mlf26

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true

# Logging Configuration
# Konsolen-Loglevel auf DEBUG erhöhen, damit die Ausgaben im stdout landen
quarkus.log.console.level=DEBUG
# Spezifisches Loglevel für Ihr Projekt-Paket auf DEBUG setzen
quarkus.log.category."net.gauntlet.locate.me".level=DEBUG
# Quarkus-eigenes File-Logging deaktivieren (verhindert doppelten Schreibzugriff)
quarkus.log.file.enable=false
